SmetaApp/Controllers/MechNameMapController.cs
using System.Web.Mvc;
using System.Linq;
using SmetaApp.Models;

namespace SmetaApp.Controllers
{
    [Authorize(Roles = RolesNames.User)]
    public class MechNameMapController : Controller
    {
        private IMechNameMapRepository Repository;
        public MechNameMapController(IMechNameMapRepository r)
        {
            Repository = r;
        }
        // POST: MechNameMap/CheckMechs
        [HttpPost]
        public ActionResult CheckMechs(string[] ms)
        {
            if (ms != null)
            {
                var mnms = Repository.MechNameMaps.ToList();
                bool[] res = ms.Select(m => mnms.Any(item => item.MechName == m)).ToArray();
                return Json(res, JsonRequestBehavior.DenyGet);
            }
            return HttpNotFound();
        }

        // POST: MechNameMap/FindMechPartial{/Name=...}
        [HttpPost]
        public ActionResult FindMechPartial(string Name)
        {
            var mechs = Repository.MechNameMaps.Where(m => m.MechName.Contains(Name));

            if (Repository.MechNameMaps.Any(m => m.MechName == Name))
                ViewBag.Match = true;
            else
                ViewBag.Match = false;

            return PartialView(mechs.Take(5).ToList());
        }
        // POST: MechNameMap/BindName(bm=...)
        [HttpPost]
        [Authorize(Roles = RolesNames.Admin)]
        public JsonResult BindName(BindingModel bm)
        {
            var Old = Repository.MechNameMaps.FirstOrDefault(m => m.MechName == bm.Old);
            var New = Repository.MechNameMaps.FirstOrDefault(m => m.MechName == bm.New);
            if (Old != null && New == null)
            {
                MechNameMap mnm = new MechNameMap()
                {
                    MechName = bm.New,
                    MechPriceName = Old.MechPriceName
                };
                Repository.CreateMechNameMap(mnm);
                return Json(bm.New+" успешно добален к "+bm.Old, JsonRequestBehavior.DenyGet);
            }
            else if (Old == null)
            {
                return Json(bm.Old + " не найден.", JsonRequestBehavior.DenyGet);
            }
            return Json(bm.New + " уже существует в БД.", JsonRequestBehavior.DenyGet);
        }
        [HttpPost]
        public ActionResult FindMechPriceByNamePartial(string Name)
        {
            var mnms = Repository.MechNameMaps.Where(mnm => mnm.MechName.Contains(Name));
            return PartialView("~/Views/MechNameMap/EditMechPrices/FindMechPriceByNamePartial.cshtml", mnms.Take(5).ToList());
        }
    }
}

SmetaApp/Controllers/MechPriceController.cs
using System.Web.Mvc;
using SmetaApp.Models;
using System.Linq;
using System.Collections.Generic;

using PagedList;

namespace SmetaApp.Controllers
{
    [Authorize(Roles = RolesNames.User)]
    public class MechPriceController : Controller
    {
        private IMechPriceRepository Repository;
        // GET: MechPrice
        public MechPriceController(IMechPriceRepository r)
        {
            Repository = r;
        }
        public ActionResult ListMechPrices(int? page,int? size)
        {
            int pageSize = size ?? 50;
            int pageNumber = page ?? 1;
            var mps = Repository.MechPrices.ToList();
            if (mps.Count>0)
                return View(mps.ToPagedList(pageNumber, pageSize));
            return HttpNotFound();
        }
        [Authorize(Roles = RolesNames.Admin)]
        public ActionResult EditMechPrices(int? page, int? size)
        {
            int pageSize = size ?? 50;
            int pageNumber = page ?? 1;
            var mps = Repository.MechPrices.ToList();
            if (mps.Count > 0)
                return View(mps.ToPagedList(pageNumber, pageSize));
            return HttpNotFound();
        }
        [HttpPost]
        [Authorize(Roles = RolesNames.Admin)]
        public ActionResult EditMechPrices(List<MechPriceToDel> mptds,int? page, int? size)
        {
            int pageSize = size ?? 50;
            int pageNumber = page ?? 1;

            var toDel = mptds.Where(mp => mp.toDel == true).Select(mp=>mp.MechPrice.Name);
            var toUp = mptds.Where(mp => mp.toDel == false&&mp.oldName==mp.MechPrice.Name).Select(mp => mp.MechPrice);
            var toUpPK = mptds.Where(mp => mp.toDel == false && mp.oldName != mp.MechPrice.Name);
            foreach (string Name in toDel)
                Repository.DeleteMechPrice(Name);
            foreach (MechPrice mp in toUp)
            {
                Repository.UpdateMechPrice(mp);
            }
            foreach(MechPriceToDel mptd in toUpPK)
            {
                if (Repository.ReadMechPrice(mptd.MechPrice.Name) == null)
                {
                    Repository.DeleteMechPrice(mptd.oldName);

                    Repository.CreateMechPrice(mptd.MechPrice);
                }
            }

            var mps = Repository.MechPrices.ToList();
            if (mps.Count > 0)
                return View(mps.ToPagedList(pageNumber, pageSize));
            return HttpNotFound();
        }
        [HttpGet]
        [Authorize(Roles = RolesNames.Admin)]
        public ActionResult EditFindMechPriceByName(string Search, int? page, int? size)
        {
            if (Search == null || Search == "")
                return RedirectToAction("EditMechPrices", "MechPrice", new { page = page, size = size });
            int pageSize = size ?? 10;
            int pageNumber = page ?? 1;
            var mps = Repository.MechPrices.Where(mp => mp.AnotherNames.Select(an=>an.MechName).Any(an => an.Contains(Search)));
            if (mps.Any())
            {
                ViewBag.Type = "Name";
                ViewBag.Search = Search;
                return View("~/Views/MechPrice/EditMechPrices.cshtml", mps.ToList().ToPagedList(pageNumber, pageSize));
            }
            return HttpNotFound();
        }
        [HttpGet]
        public ActionResult ListFindMechPriceByName(string Search, int? page, int? size)
        {
            if (Search == null || Search == "")
                return RedirectToAction("ListMechPrices", "MechPrice", new { page = page, size = size });
            int pageSize = size ?? 10;
            int pageNumber = page ?? 1;
            var mps = Repository.MechPrices.Where(mp => mp.AnotherNames.Select(an => an.MechName).Any(an => an.Contains(Search)));
            if (mps.Any())
            {
                ViewBag.Type = "Name";
                ViewBag.Search = Search;
                return View("~/Views/MechPrice/ListMechPrices.cshtml", mps.ToList().ToPagedList(pageNumber, pageSize));
            }
            return HttpNotFound();
        }

        [HttpGet]
        [Authorize(Roles = RolesNames.Admin)]
        public ActionResult AddMechPrices()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = RolesNames.Admin)]
        public void AddMechPrices(List<MechPrice> mps)
        {
            if (mps != null)
            {
                foreach (MechPrice mptd in mps)
                {
                    if (Repository.ReadMechPrice(mptd.Name) == null)
                    {
                        Repository.CreateMechPrice(mptd);
                    }
                }
            }

            //return RedirectToAction("ListMatPrices", "MatPrice", new { page = page, size = size });
        }
        [HttpPost]
        public JsonResult CheckMPs(string[] mps)
        {
            bool[] res = mps.Select(mp => Repository.MechPrices.Any(item => item.Name == mp)).ToArray();
            return Json(res, JsonRequestBehavior.DenyGet);
        }
    }
}

SmetaApp/Views/MechPrice/EditMechPrices.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@model PagedList.IPagedList<SmetaApp.Models.MechPrice>
@using PagedList.Mvc;

@{
    ViewBag.Title = "EditMechPrices";

    Func<int, string> pageFunc;
    string Action;
    if (ViewBag.Type == "Name")
    {
        Action = "EditFindMechPriceByName";
        pageFunc = page => Url.Action("EditFindMechPriceByName", new { ViewBag.Search, page, size = Model.PageSize });
    }
    else
    {
        Action = "EditMechPrices";
        pageFunc = page => Url.Action("EditMechPrices", new { page, size = Model.PageSize });
    }
}
<!--PageStart-->
<h2>EditMechPrices</h2>

<div class="find-name">
    <div><label for="findname">Поиск по наименованию:</label></div>
    <div>
        @using (Ajax.BeginForm("FindMechPriceByNamePartial", "MechNameMap", new AjaxOptions { UpdateTargetId = "results" }))
        {
            <input type="text" class="find-mech-price-by-name" name="Name" placeholder="Наименование" autocomplete="off" id="findname" />
        }
        <span id="results"></span>


        @using (Html.BeginForm("EditFindMechPriceByName", "MechPrice", FormMethod.Get, new { id = "findnameform" }))
        {
            <input type="text" hidden name="Search" />
            <input type="submit" value="Поиск" />
        }
    </div>
</div>
<script>
    let str = `<input type="button" value="X" style="display:block;margin-left:160px;" class="button-delete" onclick="delOnClick(this);" />`;

    function delOnClick(t) {
        if ($(t).closest('ol').find('li').length > 1) {
            $(t).closest('tr').addClass('changed');
            $(t).closest('li').remove();
        }
        else {
            alert('Нельзя удалить последнее из наименований для прайса');
        }
    }
</script>
@using (Html.BeginForm("EditMechPrices", "MechPrice", FormMethod.Post, new { id = "addingform" }))
{
    <table id="table" class="table">
        <tr>
            <th>
                Название
            </th>
            <th>
                Код
            </th>
            <th>
                Eur
            </th>
            <th>
                Dol
            </th>
            <th>
                Rub
            </th>
            <th>
                Скидка поставщика
            </th>
            <th>
                Другие имена
            </th>
            <th>
                Удалить?
            </th>
        </tr>

        @foreach (var MechPrice in Model)
        {
        <tr>
            <td>
                @Html.EditorFor(modelItem => MechPrice.Name)
                @Html.HiddenFor(modelItem => MechPrice.Name)
            </td>
            <td>
                @Html.EditorFor(modelItem => MechPrice.Code)
            </td>
            <td>
                @Html.EditorFor(modelItem => MechPrice.Eur)
            </td>
            <td>
                @Html.EditorFor(modelItem => MechPrice.Dol)
            </td>
            <td>
                @Html.EditorFor(modelItem => MechPrice.Rub)
            </td>
            <td>
                @Html.EditorFor(modelItem => MechPrice.Discount)
            </td>
            <td>
                <input type="button" value="Отобразить" onclick="$(this).hide(); $(this).nextAll('div').show();" />
                <div hidden>
                    <ol>
                        @foreach (var n in MechPrice.AnotherNames)
                        {
                            <li style="margin-top:10px;">
                                <input type='text' value='@n.MechName' name='n.MechName' style='width:150px;float:left;' />
                                <input type="button" value="X" style="display:block;margin-left:160px;" class="button-delete" onclick="delOnClick(this);" />
                            </li>
                        }
                    </ol>

                    <input type="button" value="+" class="button-add" onclick="$(this).prevAll('ol').append(`<li style='margin-top:10px;'><input style='width:150px;float:left;' type='text' name='n.MechName'/>`+str+`</li>`);" />
                </div>
            </td>
            <td>
                <input type='checkbox' name="toDel" value="true">
            </td>
        </tr>
        }
        

    </table>
}
Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, pageFunc)
    @using (Html.BeginForm(Action, "MechPrice", FormMethod.Get, new { id = "pagesizeform" }))
    {
        <select name="size" id="pagesize">
            <option value="10">
                10
            </option>
            <option value="50">
                50
            </option>
            <option value="100">
                100
            </option>
        </select>
        if (ViewBag.Search != "")
        {
            <input name="Search" value="@ViewBag.Search" hidden />
        }
    }
    <input type="button" id="saveresults" value="Сохранить" />
    <!--PageEnd-->

    <script>
    $("#pagesize").find("option[value='@Model.PageSize']").attr("selected", "selected");
    $("#pagesize").change(function () {
        $(this).closest("form").submit();
    });

    $("#table").find("input").change(function () {
        $(this).closest("tr").addClass("changed");
    });

    $("#saveresults").click(function () {
        let save = confirm("Сохранить изменения?");
        if (save) {
            let prices = $("#table").find("tr.changed");

            updatePrices(prices);
        }
    });

    function updatePrices(prices) {
        if (prices.length > 0) {
            let form =  $("#addingform");
            prices.each(function (i, el) {
                el = $(el);

                el.find("input[name='MechPrice.Name']").last().attr("name", "oldName");

                el.find("input:not([name='toDel'],[name='oldName'],[name='n.MechName'])").each(function (ind, inp) {
                    inp = $(inp);
                    inp.attr("name","["+i+"]."+inp.attr("name"));
                });
                el.find("input[name='toDel']").attr("name", "[" + i + "].toDel");
                el.find("input[name='oldName']").attr("name", "[" + i + "].oldName");
                el.find("input[name='n.MechName']").each(function (ind, inp) {
                    inp = $(inp);
                    inp.attr("name", "[" + i + "].MechPrice.AnotherNames["+ind+"].MechName");
                });
            });

            form.submit();
        }
    }

    //ajax search
    function hideOnFocus(id) {
        return ()=>$(id).hide();
    }

    let named = hideOnFocus("#results");
    $("#findname").bind("input", function () {
        let t = $(this);
        if (t.val() != "") {
            t.closest("form").submit();
            $("#results").show();
            $(":not(#results)").not(t).one("focus", named);
        }
        else {
            $("#results").hide();
            $(":not(#results)").not(t).off("focus", named);
        }
    });


    $("#findnameform").submit(function () {
        $(this).find("[name='Search']").val($("#findname").val());
    });
    </script>

SmetaApp/Views/MechPrice/ListMechPrices.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@model PagedList.IPagedList<SmetaApp.Models.MechPrice>
@using PagedList.Mvc;

@{
    ViewBag.Title = "ListMechPrices";

    Func<int, string> pageFunc;
    string Action;
    if (ViewBag.Type == "Name")
    {
        Action = "ListFindMechPriceByName";
        pageFunc = page => Url.Action("ListFindMechPriceByName", new { ViewBag.Search, page, size = Model.PageSize });
    }
    else
    {
        Action = "ListMechPrices";
        pageFunc = page => Url.Action("ListMechPrices", new { page, size = Model.PageSize });
    }
}
<!--PageStart-->
<h2>ListMechPrices</h2>

<div class="find-name">
    <div><label for="findname">Поиск по наименованию:</label></div>
    <div>
        @using (Ajax.BeginForm("FindMechPriceByNamePartial", "MechNameMap", new AjaxOptions { UpdateTargetId = "results" }))
        {
            <input type="text" class="find-mech-price-by-name" name="Name" placeholder="Наименование" autocomplete="off" id="findname" />
        }
        <span id="results"></span>


        @using (Html.BeginForm("ListFindMechPriceByName", "MechPrice", FormMethod.Get, new { id = "findnameform" }))
        {
            <input type="text" hidden name="Search" />
            <input type="submit" value="Поиск" />
        }
    </div>
</div>

<table class="table">
    <tr>
        <th>
            Название
        </th>
        <th>
            Код
        </th>
        <th>
            Eur
        </th>
        <th>
            Dol
        </th>
        <th>
            Rub
        </th>
        <th>
            Скидка поставщика
        </th>
        <th>
            Другие имена
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Eur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rub)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount)
            </td>
            <td>
                <input type="button" value="Отобразить" onclick="$(this).hide(); $(this).nextAll('ol').show();" />
                <ol hidden>
                    @foreach (var n in item.AnotherNames)
                    {
                        <li>"@n.MechName"</li>
                    }
                </ol>
            </td>
        </tr>
    }

</table>

Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
@Html.PagedListPager(Model, pageFunc)
@using (Html.BeginForm(Action, "MechPrice", FormMethod.Get, new { id = "pagesizeform" }))
{
    <select name="size" id="pagesize">
        <option value="10">
            10
        </option>
        <option value="50">
            50
        </option>
        <option value="100">
            100
        </option>
    </select>
    if (ViewBag.Search != "")
    {
        <input name="Search" value="@ViewBag.Search" hidden />
    }
}
<!--PageEnd-->
<script>
    $("#pagesize").find("option[value='@Model.PageSize']").attr("selected", "selected");
    $("#pagesize").change(function () {
        $(this).closest("form").submit();
    });

    //ajax search
    function hideOnFocus(id) {
        return ()=>$(id).hide();
    }

    let named = hideOnFocus("#results");
    $("#findname").bind("input", function () {
        let t = $(this);
        if (t.val() != "") {
            t.closest("form").submit();
            $("#results").show();
            $(":not(#results)").not(t).one("focus", named);
        }
        else {
            $("#results").hide();
            $(":not(#results)").not(t).off("focus", named);
        }
    });


    $("#findnameform").submit(function () {
        $(this).find("[name='Search']").val($("#findname").val());
    });
</script>